<?php
function dcm_registration_menu() {
  $items = array();
  $items['user_registration'] = array(
    'title' => t('My form'),
    'page callback' => 'dcm_registration_form',
    'access arguments' => array('access content'),
    'description' => t('My form'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}
function dcm_registration_form() {
  return drupal_get_form('dcm_registration_my_form');
}
function 

dcm_registration_my_form($form_state) {
  $form['name'] = array(
    '#type' => 'fieldset',
    '#title' => t('Name'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['name']['first'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#required' => TRUE,
    '#description' => "Please enter your first name.",
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['name']['last'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#required' => TRUE,
	'#size' => 20,
    '#maxlength' => 20,
  );
  
  $form['mobile_number'] = array(
    '#type' => 'textfield',
    '#title' => "Mobile Number",
    '#description' => 'Enter the 10-digit mobile number',
	'#required' => TRUE,
	'#size' => 10,
    '#maxlength' => 10,
  );

  $form['address'] = array(
    '#type' => 'textarea',
    '#title' => "Address",
  );  
  
  $form['age'] = array(
    '#type' => 'textfield',
    '#title' => "Age",
    '#required' => TRUE,
	'#size' => 2,
    '#maxlength' => 2,	
  );  
  
   $form['selected'] = array(
		'#type' => 'select',
		'#title' => t('Country'),
		'#options' => array(
		  1 => t('Australia'),
		  2 => t('China'),
		  3 => t('United States of America'),
		  4 => t('India'),
		  5 => t('Saudi Arabia'),
		),
		'#description' => t('Select your country of birth'),
 ); 
  
  $form['terms_conditions'] = array(
    '#type' => 'checkbox',
    '#title' => t('I Agree to Terms & Conditions '),
	'#required' => TRUE, 
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}
function dcm_registration_my_form_validate($form, &$form_state) {
    $year_of_birth = $form_state['values']['year_of_birth'];
    if ($year_of_birth && ($year_of_birth < 1900 || $year_of_birth > 2000)) {
        form_set_error('year_of_birth', 'Enter a year between 1900 and 2000.');
    }
}
// Adds a submit handler/function to our form to send a successful 
// completion message to the screen.
function dcm_registration_my_form_submit($form, &$form_state) {
    drupal_set_message(t('The form has been submitted.'));
}

function dcm_registration_block_info() {
		  $blocks = array();
		  $blocks['dcm_registration_block'] = array(
			'info' => t('Registration block'),
		  );
		  return $blocks;
			
		}			

		/**
		* Implements hook_block_view().
		*/
		function dcm_registration_block_view($delta = '') {
		  $block = array();

		  switch ($delta) {
			case 'dcm_registration_block':
			  $block['subject'] = t('Form block');
			  $block['content'] = drupal_get_form('dcm_registration_my_form');
			break;
		  }
		  return $block;
		}
?>